FROM node:24.15-bullseye

RUN apt-get update && apt-get install -y bash

RUN corepack enable
RUN corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --ignore-scripts
RUN pnpm exec playwright install --with-deps

COPY . .
