export const countryPatterns: { country: string; patterns: string[] }[] = [
  {
    country: 'antigua_and_barbuda',
    patterns: ['antigua and barbuda', 'antigua y barbuda'],
  },
  { country: 'argentina', patterns: ['argentina'] },
  { country: 'bahamas', patterns: ['bahamas'] },
  { country: 'barbados', patterns: ['barbados'] },
  { country: 'belice', patterns: ['belize', 'belice'] },
  { country: 'bolivia', patterns: ['bolivia'] },
  { country: 'brasil', patterns: ['brasil', 'brazil'] },
  { country: 'canada', patterns: ['canada', 'canadá'] },
  { country: 'chile', patterns: ['chile'] },
  { country: 'colombia', patterns: ['colombia'] },
  { country: 'costa_rica', patterns: ['costa rica'] },
  { country: 'cuba', patterns: ['cuba'] },
  { country: 'dominica', patterns: ['dominica'] },
  {
    country: 'republica_dominicana',
    patterns: [
      'republica dominicana',
      'república dominicana',
      'dominican republic',
    ],
  },
  { country: 'ecuador', patterns: ['ecuador'] },
  { country: 'el_salvador', patterns: ['el salvador'] },
  {
    country: 'estados_unidos',
    patterns: [
      'united states',
      'usa',
      'eeuu',
      'estados unidos',
      'u.s.a',
      'u.s',
    ],
  },
  { country: 'granada', patterns: ['grenada', 'granada'] },
  { country: 'guatemala', patterns: ['guatemala'] },
  { country: 'guyana', patterns: ['guyana'] },
  { country: 'haiti', patterns: ['haiti', 'haití'] },
  { country: 'honduras', patterns: ['honduras'] },
  { country: 'jamaica', patterns: ['jamaica'] },
  { country: 'mexico', patterns: ['mexico', 'méxico'] },
  { country: 'nicaragua', patterns: ['nicaragua'] },
  { country: 'panama', patterns: ['panama', 'panamá'] },
  { country: 'paraguay', patterns: ['paraguay'] },
  { country: 'peru', patterns: ['peru', 'perú'] },
  {
    country: 'san_cristobal_y_nieves',
    patterns: [
      'saint kitts and nevis',
      'san cristobal y nieves',
      'san cristóbal y nieves',
    ],
  },
  { country: 'santa_lucia', patterns: ['saint lucia', 'santa lucia'] },
  {
    country: 'san_vicente_y_las_granadinas',
    patterns: [
      'saint vincent and the grenadines',
      'san vicente y las granadinas',
    ],
  },
  { country: 'surinam', patterns: ['suriname', 'surinam'] },
  {
    country: 'trinidad_y_tobago',
    patterns: ['trinidad and tobago', 'trinidad y tobago'],
  },
  { country: 'uruguay', patterns: ['uruguay'] },
  { country: 'venezuela', patterns: ['venezuela'] },
];
